---
title: "p8105_hw5_cz2750"
author: "Congrui Zhang"
date: "2023-11-13"
output: github_document
---

```{r setup, include=FALSE}
library(readr)
library(dplyr)
library(purrr)
library(broom)
library(ggplot2)
library(tidyr)

knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

# Q1
## Data Loading and Processing
```{r}
# Loading the homicide data from the GitHub URL
homicide_data <- read_csv("homicide-data.csv")

# Creating a city_state variable and summarizing data
homicide_summary <- homicide_data %>%
  mutate(city_state = paste(city, state, sep = ", ")) %>%
  group_by(city_state) %>%
  summarize(
    total_homicides = n(),
    unsolved_homicides = sum(disposition == "Closed without arrest" | disposition == "Open/No arrest")
  )
```
## Proportion Test for Baltimore
```{r}
# Subset data for Baltimore, MD
baltimore_data <- filter(homicide_summary, city_state == "Baltimore, MD")

# Conducting the proportion test
baltimore_prop_test <- prop.test(baltimore_data$unsolved_homicides, baltimore_data$total_homicides)

# Tidying the test results
baltimore_tidy <- tidy(baltimore_prop_test)

# Extracting the estimated proportion and confidence intervals
baltimore_estimate <- baltimore_tidy %>%
  select(estimate, conf.low, conf.high)
```

## Proportion Test for All Cities
```{r}
# Function to apply prop.test to each city
prop_test_per_city <- function(total, unsolved) {
  prop_test_result <- prop.test(unsolved, total)
  tidy(prop_test_result)
}

# Applying the function to each city
citywise_results <- homicide_summary %>%
  mutate(test_results = map2(total_homicides, unsolved_homicides, prop_test_per_city)) %>%
  unnest(test_results)

# Extracting necessary details
citywise_estimates <- citywise_results %>%
  select(city_state, estimate, conf.low, conf.high)
```

## Plotting the Results
```{r}
# Creating the plot
homicide_plot <- ggplot(citywise_estimates, aes(x = reorder(city_state, estimate), y = estimate)) +
  geom_point() +
  geom_errorbar(aes(ymin = conf.low, ymax = conf.high), width = 0.2) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  labs(x = "City", y = "Proportion of Unsolved Homicides", title = "Proportion of Unsolved Homicides in U.S. Cities")

# Displaying the plot
print(homicide_plot)
```

